# Generated by Django 4.2.7 on 2023-11-16 22:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteuser',
            name='unique_information',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
