# Generated by Django 4.2.7 on 2024-01-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_websiteuser_unique_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteuser',
            name='feature_vector',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
